server:
  port: 8081

spring:
  application:
    name: Auth
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #create/update/validate/create-drop
    properties.hibernate:
      show_sql: true
      format_sql: true

jwt:
  refresh-token:
    cookie: "__Secure-Refresh-Token"
    expires-in: 2592000
  access-token:
    cookie: "__Secure-Access-Token"
    expires-in: 900
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG